### ISSUE TITLE
Last item header

### ISSUE THREAD

**Issue by toregua** [renefloor/side_header_list_view#1]
First thank you very much for your nice component :)

I have tried to use it with success but if the last item have a different header from the previous header, the last header is not showed.

Just do that to reproduce : 
```
 hasSameHeader: (int a, int b) {
                      return false;
                  },
```
with each item having a different header

**Comment by renefloor** [comment]
Thank you toregua for reporting this issue. I will look at that next week.

**Comment by renefloor** [comment]
I just made a release with a fix for this issue. This is solved in 8f6c0f57f632b258c56b0e2061c2924977c0eb0b and released in 0.0.2

**Comment by toregua** [comment]
Nice job thank you very much. I thnking about making a pull-request about add availibity to add infinite scroll callback function soon ;)

**Comment by renefloor** [comment]
Nice. I am looking forward to your pull request.
